
* Введение
Проект *vse-gost* предназначен для разбора информации о ГОСТ, размещенной на
сайте [[http://vsegost.com]].

Здесь приведена [[./org/catalog.org][структура каталогов]] сайта vsegost.com.

* Проект *vse-gost* содержит инструкции по:
1. [[./org/instruction-mirroring.org][Зеркалированию сайта vse-gost.com]]
2. [[./org/instruction-import-file.org][Генерированию файла импорта для ДБ PostgreSQL]]
3. [[./org/instruction-postgesql.org][Установке и настройке PostgreSQL]]
4. [[./org/instruction-gost.org][Созданию базы данных gost]]
5. [[./org/instruction-build-web-app.org][Сборке выполняемого файла, запускающего веб-сервер]]
6. [[file:org/instruction-start-web-app.org][Запуску веб приложения]]
* Конвертирование gif-файлов в формат pdf 
Конвертирование gif-файлов в формат pdf - можно выполнить сторонней
утилитой gif_to_pdf.sh из пакета
[[https://github.com/mnasoft/convert_git_to_pdf/]].

* Последующие действия
См. проект vse-gost/web.

* Запуск сервера
В отдельной консоли необходимо выполнить
#+begin_src shell
  vsegost-web-tmux.sh
#+end_src

* Standalone сборка/установка (Linux)
Для standalone используется SBCL-образ без параметра =:toplevel=.
Запуск выполняется командой:
#+begin_src shell
  vsegost-web.exe --eval "(vse-gost/web:start-gosts)"
#+end_src

Основной скрипт управления standalone: =INSTALL.run= (в корне проекта).

** Сборка + установка (рекомендуется)
#+begin_src shell
  ./INSTALL.run build
  ./INSTALL.run install
#+end_src

Без аргументов скрипт показывает справку:
#+begin_src shell
  ./INSTALL.run
#+end_src

Будут установлены команды в =/usr/local/bin=:
- =vsegost-web.exe=       (standalone бинарник)
- =vsegost-web.sh=        (обертка запуска)
- =vsegost-web-tmux.sh=   (запуск в tmux)
- =vsegost-web-mk-service.sh= (генерация/установка systemd unit)

** Только сборка
#+begin_src shell
  ./INSTALL.run build
#+end_src

Артефакты сборки появляются в =src/web/sh/build/=.

** Только установка
#+begin_src shell
  ./INSTALL.run install
#+end_src

** Удаление standalone из /usr/local/bin
#+begin_src shell
  ./INSTALL.run uninstall
#+end_src

** Очистка артефактов сборки
#+begin_src shell
  ./INSTALL.run clean
#+end_src

** Установка systemd-сервиса
#+begin_src shell
  ./INSTALL.run service-install
#+end_src

** Статус systemd-сервиса
#+begin_src shell
  ./INSTALL.run service-status
#+end_src

** Удаление systemd-сервиса
#+begin_src shell
  ./INSTALL.run service-uninstall
#+end_src

** Запуск standalone
Обычный запуск:
#+begin_src shell
  vsegost-web.sh
#+end_src

Прямой запуск бинарника:
#+begin_src shell
  vsegost-web.exe --eval "(vse-gost/web:start-gosts)"
#+end_src

Запуск в tmux:
#+begin_src shell
  vsegost-web-tmux.sh
#+end_src

Опционально можно задать имя tmux-сессии:
#+begin_src shell
  SESSION_NAME=vsegost-web vsegost-web-tmux.sh
#+end_src
* [[file:org/n133906.org]]
