
* Назначение
Проект предназначен для разбора информации о ГОСТ, размещенной на
сайте [[http://vsegost.com]]. В результате разбора можно сформировать
файл, предназначенный для импорта в базу данных.

* Зависимости
Для ковертирования файлов с расширением gif в файлы с расширением pdf
используется соманда *convert*.
#+begin_src shell
sudo apt install graphicsmagick-imagemagick-compat
#+end_src

* Информация о каталогах сайта vsegost.com
Информация о ГОСТ, размещенная на сайте vsegost.com, содержится в
нескольких каталогах:
#+begin_src shell
  find ~/public_html/vsegost.com -maxdepth 1 -type d
#+end_src

#+RESULTS:
| /home/mna/public_html/vsegost.com             |
| /home/mna/public_html/vsegost.com/js          |
| /home/mna/public_html/vsegost.com/Data        |
| /home/mna/public_html/vsegost.com/Catalog     |
| /home/mna/public_html/vsegost.com/icons       |
| /home/mna/public_html/vsegost.com/Categories  |
| /home/mna/public_html/vsegost.com/DataTN      |
| /home/mna/public_html/vsegost.com/css         |
| /home/mna/public_html/vsegost.com/NCategories |

** Catalog
В подкаталогах директория Catalog хранятся файлы с расширением *.shtm,
в которых присутствует информация содержащая:
- обозначение ГОСТ;
- наименование ГОСТ;
- краткое описание ГОСТ.

** Data
В подкаталогах директория Data хранятся файлы с расширением *.gif, с
отсканированными страницами ГОСТ.

* Цели:
- Разбор содержимого зеркалированного сайта vsegost.com и формирование
  базы данных ГОСТ;
- Конвертирование gif-файлов в формат pdf - можно выполнить сторонней
  утилитой gif_to_pdf.sh из пакета
  [[https://github.com/mnasoft/convert_git_to_pdf/]].
- Создание сайта, содержащего pdf ГОСТов.

* Проект vse-gost предназначен для:
1. Генерации скрипта, выполняющего заполнение данными таблицы базы
   данных PostgreSQL, которая содержит, обозначения ГОСТов,
   наименования ГОСТов, описания ГОСТов и данные о расположении
   pdf-файлов, содержащих ГОСТы
2. Генерации скрипта, выполняющего преобразование gif-файлов,
   содержащих постраничное отображение ГОСТов, в pdf-файлы, содержащих
   отображение гостов целиком.

* ИНСТРУКЦИЯ

** Переход в рабочий каталог для зеркалирования (bash)
#+begin_src shell
cd ~/public_html
#+end_src

* Зеркалирование (bash)
#+begin_src shell
  # wget -m -np http://vsegost.com/
  # wget -c -q --mirror --convert-links --adjust-extension --page-requisites --no-parent http://vsegost.com
  wget -с --mirror --convert-links --adjust-extension --page-requisites --no-parent --quiet --no-clobber --random-wait http://vsegost.com
#+end_src

* Настройка postgreSQL

** Для создания файла импорта в PostgreSQL выполнте следующее:
   
#+begin_src lisp
  (in-package :vse-gost)

  (defparameter *files*
    (directory
     "/home/mna/public_html/vsegost.com/Catalog/*/*.shtml.html")
    "Список файлов, в которых присутствует информация о ГОСТ."
    )

  (defparameter *out-file*
     (concatenate 'string
                (uiop:getenv "HOME")
                "/"
                "out.txt"))

  (create-sql-import-file *out-file* (namestring *vsegost-Catalog*))

  (list (list "out-file" *out-file*)
        (list "vsegost-Catalog" (namestring *vsegost-Catalog*))
        (list "vsegost-Data" (namestring *vsegost-Data*))
        (list "GOST number" (length *files*)))
#+end_src

#+RESULTS:
| out-file        | /home/mna/out.txt                          |
| vsegost-Catalog | /home/mna/public_html/vsegost.com/Catalog/ |
| vsegost-Data    | /home/mna/public_html/vsegost.com/Data/    |
| GOST number     | 48371                                      |

** TODO Преобразование gif-файлов gost.pdf

Для создания файла скрипта, преобразующего gif-файлы каждого каталога
в файл gost.pdf

#+begin_src lisp
(vse-gost:main-create-bash-script-gif-pdf-convertion vse-gost:*vsegost-Data*)
#+end_src
Примечание: Примерное время выполнения сценария 5 минут.

** TODO Примеры переноса файлов на сервер
#+begin_src shell
rsync -avzh --progress /home/namatv/public_html/2015-12-21-vsegost.com/Data/ root@192.168.0.110:/home/namatv/public_html/2015-12-21-vsegost.com/Data/

rsync -azh --info=progress2 /home/namatv/public_html/2015-12-21-vsegost.com/Data/ root@192.168.0.110:/home/namatv/public_html/2015-12-21-vsegost.com/Data/

rsync -avzh --progress /home/namatv/out.txt root@192.168.0.110:/home/namatv/
#+end_src

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

* Создание базы данных gost
** Сервере mnasoft-pi для пользователя namatv
*** Переходим в запись postgres
#+begin_src shell
namatv@mnasoft-pi:~$ sudo su - postgres
#+end_src

*** Создаем роль namatv
#+begin_src shell
  postgres@mnasoft-pi:~$ createuser -dsRP namatv
#+end_src

*** Создаем для владельца namatv базу gost
#+begin_src shell   
namatv@mnasoft-pi:~$ createdb -O namatv gost
#+end_src

*** Входим в консоль postgresql
#+begin_src shell 
namatv@mnasoft-pi:~$ psql -d gost -U namatv
#+end_src

*** Создаем таблицу gost
#+begin_src sql
gost=# 
CREATE TABLE public.gost
(
  id serial PRIMARY KEY,                                        -- Идентификатор записи
  designation text,                                             -- Обозначение Стандарта.
  name text,                                                    -- Наименование Стандарта.
  description text,                                             -- Краткиое описание Стандарта
  local_path text,                                              -- Путь к документу на локальном сервере.
  external_path text,                                           -- Путь к документу на удалённом сервере.
  date date,
  status text
)
WITH (
  OIDS=FALSE
);
ALTER TABLE public.gost
  OWNER TO namatv;
COMMENT ON COLUMN public.gost.id IS            'Идентификатор записи.';
COMMENT ON COLUMN public.gost.designation IS   'Обозначение Стандарта';
COMMENT ON COLUMN public.gost.name IS          'Наименование Стандарта';
COMMENT ON COLUMN public.gost.description IS   'Краткиое описание Стандарта';
COMMENT ON COLUMN public.gost.local_path IS    'Путь к документу на локальном сервере.';
COMMENT ON COLUMN public.gost.external_path IS 'Путь к документу на удалённом сервере.';
#+end_src
*** Импортируем содержимое таблицы gost из файла:
#+begin_src sql   
  gost=# 
  copy gost (local_path, designation, date, name, description, status)
       from '/home/namatv/out.txt';
  copy gost (local_path, designation, date, name, description, status)
  from 'D:\PRG\msys32\home\namatv\quicklisp\local-projects\clisp\vse-gost\out_1.txt';
#+end_src
** Сервере mnasoft-02 для пользователя mna

*** Проверяем работу сервиса postgresql.service
Проверяем работу сервиса

#+begin_src shell
  systemctl status postgresql.service
#+end_src

#+begin_src shell
  sudo -iu postgres
  initdb --locale=ru_RU.UTF-8 --encoding=UTF8 -D /var/lib/postgres/data --data-checksums
#+end_src

*** Запускаем postgresql.service

#+begin_src shell
  sudo systemctl enable postgresql.service
  sudo systemctl start  postgresql.service
#+end_src

*** Создаем роль mna
#+begin_src shell
  sudo -iu postgres
  createuser -dsRP mna 
#+end_src

*** Создаем БД

#+begin_src shell
  sudo -iu mna
  createdb -O mna gost
#+end_src

*** Входим в консоль postgresql
#+begin_src shell
  sudo -iu mna
  psql -d gost -U mna
#+end_src

*** Создаем таблицу gost
В базе данных gost создаем таблицу gost.

Примечание: поле external_path - удалено. 

#+begin_src sql
  CREATE TABLE public.gost
  (
    id serial PRIMARY KEY,  -- Идентификатор записи;
    designation text,       -- Обозначение Стандарта;
    name text,              -- Наименование Стандарта;
    description text,       -- Краткиое описание Стандарт;
    local_path text,        -- Путь к документу на локальном сервере;
    date date,              -- Дата;
    status text             -- Дествует или нет.
  )
  WITH (
    OIDS=FALSE
  );

  ALTER TABLE public.gost OWNER TO mna;

  COMMENT ON COLUMN public.gost.id IS            'Идентификатор записи.';

  COMMENT ON COLUMN public.gost.designation IS   'Обозначение Стандарта';

  COMMENT ON COLUMN public.gost.name IS          'Наименование Стандарта';

  COMMENT ON COLUMN public.gost.description IS   'Краткиое описание Стандарта';

  COMMENT ON COLUMN public.gost.local_path IS    'Путь к документу на локальном сервере';
#+end_src

*** Импортируем содержимое таблицы gost из файла:

#+begin_src sql   
  \copy gost (local_path, designation, date, name, description, status)
  from '/home/mna/out.txt';       
#+end_src

* Запуск веб на удаленном сервере
